### PR TITLE
Add modsign verify

### PR DESCRIPTION
**Pull request by lcp**
For https://github.com/openSUSE/pesign-obs-integration/pull/11

### CODE REVIEW

**Comment by lcp** [comment]
@mwilck @bluca Would you mind to review this change?
I also build the package in my branch:
https://build.opensuse.org/package/show/home:gary_lin:branches:Base:System/pesign-obs-integration

**Comment by mwilck** [comment]
I had the same glitch in my own PR - could you replace

    Conflicts:      suse-module-tools <= 15.0.10

with 

    Requires:      suse-module-tools >= 15.0.10

?? That way I could call the next suse-module-tools version "15.0.10", and "Requires:" is IMO better than "Conflicts:"

Otherwise, looks great.

**Comment by lcp** [comment]
done. I'm trying to build some packages with the updated pesign-obs-integration to verify the change.

**Comment by lcp** [comment]
My test looks good. Merge the change.

**Comment by mwilck** [comment]
Thanks. Please hold back a factory submission for now. Some more discussion may be necessary.

**Comment by mwilck** [comment]
Created FATE 326985 about the similar case of the "modhash" tool. Unless "modhash" can also be moved out of suse-module-tools, moving "modsign-verify" to pesign-obs-integration doesn't make a lot of sense. Sorry, I'd overlooked that and only just realized when I started working on the removal of "modsign-verify".

**Comment by bluca** [comment]
> @mwilck @bluca Would you mind to review this change?
> I also build the package in my branch:
> https://build.opensuse.org/package/show/home:gary_lin:branches:Base:System/pesign-obs-integration

Hi,

I checked the Debian packages and they all look good, thanks.

**Comment by lcp** [comment]
@mwilck @bluca Thank you all :-D
I merged my SR in OBS:
https://build.opensuse.org/request/show/657499

**Comment by mwilck** [comment]
@lcp, you've fixed two whitespace errors when you merged modsign-verify.

That's allright in general, but in this case it poses a risk, because now the files in suse-module-tools and pesign-obs-integration aren't binary-identical any more. That means that we have a potential rpm file conflict if ever a situation arises that the "old" suse-module-tools and the "new" pesign-obs-integration (both including modsign-verify) are to be installed on the same system. If you had just left the whitespace errors in place, that couldn't happen, because rpm has no problem with two packages shipping identical files. In that case we wouldn't need any Requires: or Conflicts: tags.

So now we have to take extra care that this sitaution won't arise.

**Comment by mwilck** [comment]
Here's what I'll do. I'll revert the change removing modsign-verify in suse-module-tools for now, and I'll copy your modsign-verify version (with the whitespace fixes) to suse-module-tools.

That means we can submit independently. Once your version is safely out on all distros where we want to make the move (my suggestion is TW, SLE15-SP1, Leap 15.1), I can remove the file in suse-module-tools.

**Comment by mwilck** [comment]
Argh, Dominique was faster than I and already accepted the suse-module-tools request.

So, I've now submitted https://build.opensuse.org/request/show/670420 on your behalf. I hope that's ok for you.

**Comment by lcp** [comment]
@mwilck  Thanks for handling that!

**Pull request merged**
