### PR TITLE
Use pesign for signing on riscv64

### PR DESCRIPTION
**Pull request by andreas-schwab**

### CODE REVIEW

**Comment by hramrach** [comment]
Is pesign built for riscv64?

**Comment by andreas-schwab** [comment]
Of course it is.  Why do you ask?

**Comment by hramrach** [comment]
Indeed: ExclusiveArch:  ia64 %ix86 x86_64 aarch64 %arm riscv64

**Comment by dirkmueller** [comment]
There was enough time for feedback, merging

**Pull request merged**
