### PR TITLE
kernel-sign-file: Add padding support.

### PR DESCRIPTION
**Pull request by hramrach**
Fixes: 13efe22 ("Support ppc grub signing (jsc#SLE-18271 bsc#1192764).")

This should fix placement of the padding in the signature.

### CODE REVIEW

**Comment by hramrach** [comment]
@daxtens @joeyli 

This adds the padding after the fully built signature but I still cannot boot the signed binary with secure boot enabled.

**Comment by hramrach** [comment]
Built both grub and kernel with this latest kernel-sign-file and can boot in secure mode.

**Comment by joeyli** [comment]
I have reviewed Support ppc grub signing patch. It's good to me.

**Review by joeyli — APPROVED** [review]
reviewed

**Review by joeyli — APPROVED** [review]
reviewed

**Review by joeyli — CHANGES_REQUESTED** [review]
Hi Michal, 

I prefer that do not using a fixed number 40 bytes for footer_size. I think that the foot_size is:
foot_size = module_signature size (12 bytes) + MODULE_SIG_STRING size (28 bytes)

If the size of module_signature structure be changed in kernel then the fixed 40 number must also be changed. It's hard to know we need to change the number in pesign-repackage.spec.in in the future. 
So I suggest that we still using .appendtest approach to calculate the size of footer

Thanks a lot!

**Review by joeyli — APPROVED** [review]

**Review by joeyli — APPROVED** [review]
reviewed

**Comment by hramrach** [comment]
> Hi Michal,
> 
> I prefer that do not using a fixed number 40 bytes for footer_size. I think that the foot_size is: foot_size = module_signature size (12 bytes) + MODULE_SIG_STRING size (28 bytes)
> 
> If the size of module_signature structure be changed in kernel then the fixed 40 number must also be changed. It's hard to know we need to change the number in pesign-repackage.spec.in in the future. So I suggest that we still using .appendtest approach to calculate the size of footer

If the structure is changed then the sign-file needs changing. Also we have a test pesign-repackage.spec.in that tests that the signed size matches this footer size so any such change will be caught.

**Comment by hramrach** [comment]
Also it is very unlikely to change. The structure has been kept the same for backwards compatibility when moving to PKCS#7 signatures although most of the fields are meaningless now because the data is included in the signature.

**Review by joeyli — APPROVED** [review]
Approved here. I will add another patch to comment that 
40 bytes = foot_size is: foot_size = module_signature size (12 bytes) + MODULE_SIG_STRING size (28 bytes)

**Pull request merged**
